(lang dune 3.20)

(name tenThousandthFirstPrime)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name tenThousandthFirstPrime)
 (synopsis "Project Euler tasks: 10001st prime and permutations")
 (description
  "Implementations for Project Euler problems 7 and 24 with multiple functional styles.")
 (depends
  ocaml
  (alcotest :with-test)
  (ocamlformat :with-test))
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
